# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8269599ab077d0d50265b566b006e5fe7d5ab0aef248c018a503e37b28f832594e3238c0cb9f02d9abbc4ce2627a08da624400e00340a4d396a537ea7619a39a

test:
  secret_key_base: ab155f98744a6028c5226616d0691c87d72682d4a417f78349a783bf3bd1fe8fe7b4b70079296717a0436453ea77db46031a1df65998816fd66e0992eb64d4fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
